services:
  # El mensajero temporal (se queda en local)
    redis-server:
        image: redis:alpine

    ingest-api:
        build: ./ingest_api
        ports:
            - "8000:8000"
        env_file:
            - .env
        command: python main.py  # <--- ESTO MANTIENE EL PROCESO VIVO
        depends_on:
            - redis-server

    metrics-worker:
        build: ./metrics_worker
        env_file:
            - .env
        command: python worker.py # <--- Y AQUÍ TAMBIÉN
        depends_on:
            - redis-server

    query-api:
        build: ./query_api
        ports:
            - "8001:8001"
        env_file:
            - .env
        command: python main.py # <--- Y AQUÍ TAMBIÉN